// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXksHkTdfL5Q8v_3UgjuhZTosSIMmzIRo',
    appId: '1:289046200539:web:c51f8f7afd0621824b4cfe',
    messagingSenderId: '289046200539',
    projectId: 'moneytracker-5fedb',
    authDomain: 'moneytracker-5fedb.firebaseapp.com',
    storageBucket: 'moneytracker-5fedb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDfIAV76LnyGcNQ-ho_T-DKj3sSvUM_4',
    appId: '1:289046200539:android:ca08258457ad70ed4b4cfe',
    messagingSenderId: '289046200539',
    projectId: 'moneytracker-5fedb',
    storageBucket: 'moneytracker-5fedb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgiYMjMYX0oeV0t4LniwwZOZyfzqpN4eE',
    appId: '1:289046200539:ios:6004c0f1cc69dee44b4cfe',
    messagingSenderId: '289046200539',
    projectId: 'moneytracker-5fedb',
    storageBucket: 'moneytracker-5fedb.firebasestorage.app',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgiYMjMYX0oeV0t4LniwwZOZyfzqpN4eE',
    appId: '1:289046200539:ios:6004c0f1cc69dee44b4cfe',
    messagingSenderId: '289046200539',
    projectId: 'moneytracker-5fedb',
    storageBucket: 'moneytracker-5fedb.firebasestorage.app',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXksHkTdfL5Q8v_3UgjuhZTosSIMmzIRo',
    appId: '1:289046200539:web:bbe2712ea58a00714b4cfe',
    messagingSenderId: '289046200539',
    projectId: 'moneytracker-5fedb',
    authDomain: 'moneytracker-5fedb.firebaseapp.com',
    storageBucket: 'moneytracker-5fedb.firebasestorage.app',
  );
}
